// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjUS1psPB-UzWtj3iRXVMzItq1-cUnWso',
    appId: '1:730023418673:web:31c37e69c9b9f79d78ee10',
    messagingSenderId: '730023418673',
    projectId: 'employee-db-860c1',
    authDomain: 'employee-db-860c1.firebaseapp.com',
    databaseURL: 'https://employee-db-860c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-860c1.firebasestorage.app',
    measurementId: 'G-JBCCJ6M6NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjuoOB5gWNUNUr7rwPaQcOb4SBnAWpQl8',
    appId: '1:730023418673:android:82c1e9005d47bbef78ee10',
    messagingSenderId: '730023418673',
    projectId: 'employee-db-860c1',
    databaseURL: 'https://employee-db-860c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-860c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUK3zjoa0v6E_W2Pvmy1_BqgWeUK_bqCQ',
    appId: '1:730023418673:ios:b3f401625a49eed178ee10',
    messagingSenderId: '730023418673',
    projectId: 'employee-db-860c1',
    databaseURL: 'https://employee-db-860c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-860c1.firebasestorage.app',
    iosBundleId: 'com.example.employeeEvangunawan2327240016',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUK3zjoa0v6E_W2Pvmy1_BqgWeUK_bqCQ',
    appId: '1:730023418673:ios:b3f401625a49eed178ee10',
    messagingSenderId: '730023418673',
    projectId: 'employee-db-860c1',
    databaseURL: 'https://employee-db-860c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-860c1.firebasestorage.app',
    iosBundleId: 'com.example.employeeEvangunawan2327240016',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjUS1psPB-UzWtj3iRXVMzItq1-cUnWso',
    appId: '1:730023418673:web:ca98a5421a2fcf0978ee10',
    messagingSenderId: '730023418673',
    projectId: 'employee-db-860c1',
    authDomain: 'employee-db-860c1.firebaseapp.com',
    databaseURL: 'https://employee-db-860c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-860c1.firebasestorage.app',
    measurementId: 'G-PD0ED2Y131',
  );
}
